# Generated by Django 5.0.4 on 2024-07-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
    ]
