# Generated by Django 5.0.4 on 2024-07-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_baseuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='balance',
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
    ]
