# Generated by Django 5.0.4 on 2024-07-29 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_baseuser_balance_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.IntegerField(default=12, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
            preserve_default=False,
        ),
    ]
