# Generated by Django 5.0.4 on 2024-08-22 12:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_group_duration_group_end_date_group_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[500, 500], upload_to='user/%Y/%m', verbose_name='image'),
        ),
    ]
