# Generated by Django 5.0.4 on 2024-10-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_baseuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lesson',
        ),
    ]
