# Generated by Django 5.0.4 on 2024-11-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
    ]
