# Generated by Django 5.0.4 on 2024-11-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('superuser', 'Superuser')], max_length=12, verbose_name='user role'),
        ),
    ]
