# Generated by Django 5.0.4 on 2024-11-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_baseuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_date', models.DateField(verbose_name='homework date')),
                ('type', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not done')], max_length=250, verbose_name='homework type')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='common.group', verbose_name='group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='common.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homework',
                'db_table': 'homework',
            },
        ),
    ]
