# Generated by Django 5.0.4 on 2024-11-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='common.task', verbose_name='task'),
        ),
    ]
