# Generated by Django 5.0.4 on 2024-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_homework_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('done', 'Done'), ('not_done', 'Not done'), ('not_checked', 'Not checked')], default='not_checked', max_length=250, verbose_name='homework type'),
        ),
    ]
